front eto govno
Vaytsekhovskiy/rentalPremises pull request #5
Opened 2024-04-12 18:27 UTC by ReFlex-cmd

Вроде б полностью сделан фронт в репе

2024-04-12 18:45 UTC, Vaytsekhovskiy requested changes
Кароче, исправь по возможности замечания и сделай другой push, следующий push попадёт в этот пул реквест, я его не закрываю

2024-04-12 18:45 UTC, Vaytsekhovskiy commented on src/main/java/ru/magniti/rentalPremises/services/BuildingService.java
> -    public void deleteBuilding(long id) {
Блять, зачем удалил?

2024-04-12 18:45 UTC, Vaytsekhovskiy commented on src/main/java/ru/magniti/rentalPremises/services/UserService.java
> +        user.getRoles().add(Role.ROLE_ADMIN); // здесь можно поменять на ROLE_ADMIN
Поставль ROLE_USER обратно

2024-04-12 18:45 UTC, Vaytsekhovskiy commented on src/main/resources/application.properties
> -spring.application.name=rentalPremises
добавь application.properties в gitignore, чтобы не выкладывать этот файл

2024-04-12 18:45 UTC, Vaytsekhovskiy commented on src/main/resources/templates/admin.ftlh
> -    <#else>
Добавь этот else в реализацию. Просто, если не будет никаких пользователей, то возникнет ошибка

2024-04-12 18:45 UTC, Vaytsekhovskiy commented on src/main/resources/templates/zvzvzvz.ftlh
> +<!DOCTYPE html>
А чё это за файл? Нахуя нужен?

2024-04-13 09:55 UTC, ReFlex-cmd commented on src/main/java/ru/magniti/rentalPremises/services/BuildingService.java
> -    public void deleteBuilding(long id) {
У меня вроде осталось...

2024-04-13 15:31 UTC, Vaytsekhovskiy requested changes

2024-04-13 15:31 UTC, Vaytsekhovskiy commented on src/main/java/ru/magniti/rentalPremises/controllers/ImageController.java
> +                .header("fileName", image.getOriginalFileName())
Original name больше нет в бд, поэтому эту строку надо удалить

2024-04-13 15:31 UTC, Vaytsekhovskiy commented on src/main/java/ru/magniti/rentalPremises/models/Building.java
> +    @ManyToOne(cascade = CascadeType.REFRESH, fetch = FetchType.EAGER)
А зачем обратно на EAGER? Если оставить EAGER, то возникает ошибка при удалении здания, нужно на LAZY поменять

2024-04-13 15:31 UTC, Vaytsekhovskiy commented on src/main/java/ru/magniti/rentalPremises/models/Image.java
> +    @Column(name = "originalFileName")
Тоже нужно удалить, т.к. это колонка генерит кучу ошибок, но по факту она не нужа

2024-04-13 15:31 UTC, Vaytsekhovskiy commented on src/main/java/ru/magniti/rentalPremises/repositories/BuildingRepository.java
> -    List<Building> findBuildingByLocation(String location);
А это зачем удалять? без этого метода не будут работать фильтры, которые реализовал даня

2024-04-13 15:39 UTC, Vaytsekhovskiy approved these changes

2024-04-13 15:54 UTC, merged